export const machineNames: string[] = [
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
  "***REMOVED***",
]
